
const char* server_url = "https://consentiuminc.online/api/board/updatedata/?";

// const char* consentium_root_ca = \
// "-----BEGIN CERTIFICATE-----\n" \
// "MIIERDCCAyygAwIBAgISA/KuXdYkBk8NoqZHazIHP9e0MA0GCSqGSIb3DQEBCwUA\n" \
// "MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD\n" \
// "EwJSMzAeFw0yMzA4MDYwNTAyMTdaFw0yMzExMDQwNTAyMTZaMB8xHTAbBgNVBAMT\n" \
// "MDEyNzEyNDgwOFoXDTI0MTIzMTIzNTk1OVowSjELMAkGA1UEBhMCVVMxGTAXBgNV\n" \
// "BAoTEENsb3VkZmxhcmUsIEluYy4xIDAeBgNVBAMTF0Nsb3VkZmxhcmUgSW5jIEVD\n" \
// "QyBDQS0zMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEua1NZpkUC0bsH4HRKlAe\n" \
// "nQMVLzQSfS2WuIg4m4Vfj7+7Te9hRsTJc9QkT+DuHM5ss1FxL2ruTAUJd9NyYqSb\n" \
// "16OCAWgwggFkMB0GA1UdDgQWBBSlzjfq67B1DpRniLRF+tkkEIeWHzAfBgNVHSME\n" \
// "GDAWgBTlnVkwgkdYzKz6CFQ2hns6tQRN8DAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0l\n" \
// "BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1UdEwEB/wQIMAYBAf8CAQAwNAYI\n" \
// "KwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5j\n" \
// "b20wOgYDVR0fBDMwMTAvoC2gK4YpaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL09t\n" \
// "bmlyb290MjAyNS5jcmwwbQYDVR0gBGYwZDA3BglghkgBhv1sAQEwKjAoBggrBgEF\n" \
// "BQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzALBglghkgBhv1sAQIw\n" \
// "CAYGZ4EMAQIBMAgGBmeBDAECAjAIBgZngQwBAgMwDQYJKoZIhvcNAQELBQADggEB\n" \
// "AAUkHd0bsCrrmNaF4zlNXmtXnYJX/OvoMaJXkGUFvhZEOFp3ArnPEELG4ZKk40Un\n" \
// "+ABHLGioVplTVI+tnkDB0A+21w0LOEhsUCxJkAZbZB2LzEgwLt4I4ptJIsCSDBFe\n" \
// "lpKU1fwg3FZs5ZKTv3ocwDfjhUkV+ivhdDkYD7fa86JXWGBPzI6UAPxGezQxPk1H\n" \
// "goE6y/SJXQ7vTQ1unBuCJN0yJV0ReFEQPaA1IwQvZW+cwdFD19Ae8zFnWSfda9J1\n" \
// "CZMRJCQUzym+5iPDuI9yP+kHyCREU3qzuWFloUwOxkgAyXVjBYdwRVKD05WdRerw\n" \
// "6DEdfgkfCv4+3ao8XnTSrLE=\n" \
// "-----END CERTIFICATE-----\n" ;


const char* consentium_root_ca = 
"-----BEGIN CERTIFICATE-----\n"
"MIIERDCCAyygAwIBAgISA/KuXdYkBk8NoqZHazIHP9e0MA0GCSqGSIb3DQEBCwUA\n"
"MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD\n"
"EwJSMzAeFw0yMzA4MDYwNTAyMTdaFw0yMzExMDQwNTAyMTZaMB8xHTAbBgNVBAMT\n"
"FGNvbnNlbnRpdW1pbmMub25saW5lMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\n"
"ZRWW7wbBKjZeQYGp6JPk6EiDyBftpzJ+/iTtRuSTRZTaJwL0jvq4Nz4R0gsbRVux\n"
"UlxFW8GvSdRndLZiCCKRGaOCAjAwggIsMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUE\n"
"FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU\n"
"Pt1I2hGWCe6emT6OPgDOzJlnIM8wHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+v\n"
"nYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5s\n"
"ZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wOQYD\n"
"VR0RBDIwMIIUY29uc2VudGl1bWluYy5vbmxpbmWCGHd3dy5jb25zZW50aXVtaW5j\n"
"Lm9ubGluZTATBgNVHSAEDDAKMAgGBmeBDAECATCCAQQGCisGAQQB1nkCBAIEgfUE\n"
"gfIA8AB2AHoyjFTYty22IOo44FIe6YQWcDIThU070ivBOlejUutSAAABiclwdYQA\n"
"AAQDAEcwRQIhAMM9B+0kNa2mn5chU3psOS8a84zFR285kJutfrFtJjVOAiAfn1qg\n"
"Ub64Tf+tYXpwfpn9u4EipLjNDZqeYKm19RY7pgB2AK33vvp8/xDIi509nB4+GGq0\n"
"Zyldz7EMJMqFhjTr3IKKAAABiclwdZkAAAQDAEcwRQIhAId4XUe6X01DTUjnYKse\n"
"xaU/0GhuJSEsahG/h7joOnggAiBFB3aBtpe3Iht+v8mjUmnGYPMRcdVyiWNXeDMg\n"
"YFF60DANBgkqhkiG9w0BAQsFAAOCAQEAWhaAksavEQkkzkEnV1pqxwQ+43ZWTiaN\n"
"PR65P7j4pLugc2xDwvf9v1JXvmOiNdmrmMztrvfOY8/ufBa4Wl5c+RxWEEZH+axx\n"
"jE2aDhoSW+7o5y35qD7T6794h61ZJclGBPlDMbDz4OZKCDmGORw4vcHB1bjn93K8\n"
"HID1CMBvdbtctIbhImJsKSsGJWxwVvXbwicy3nCAVAr7FRIwwAtLzsi8RJYAbisn\n"
"Ssp824xkDE9a14wGpkZ+ZgjihbOjLvGqY7HbSiL65SmTkOEBjbSfMs4iE6cDjZFU\n"
"eR39xTB6hBjUtEFfxpZokLD6mnNOm0CrnDRobhcMWlwBm0JV4IjLcg=="
"-----END CERTIFICATE-----\n";


